language: perl

sudo: false
fast_finish: true
install: "echo"
dist: xenial
jdk: openjdk11

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

script:
    - perl Configure.pl $NQP_OPTIONS
    - make test
    - make install

branches:
   only:
     - master
     - /smoke-me/

notifications:
  irc:
    channels:
    - "irc.freenode.net#raku-dev"
    on_success: change
    on_failure: always
    template:
      - "NQP build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"


env:
  matrix:
    - NQP_OPTIONS="--gen-moar"
    - NQP_OPTIONS="--gen-moar=master"
    - NQP_OPTIONS="--backends=jvm"

#matrix:
#  allow_failures:
#    - env: NQP_OPTIONS="--backends=jvm"
